### ISSUE TITLE
Corrección de ubicacion del archivo de sesión02

### ISSUE THREAD

**Issue by jevillanueva** [Brayanex14/psg-example#1]
Correcciones hasta el momento :D

El archivo: retos_sesion_01/sesion02.md

Deberia estar afuera no dentro la carpeta no dentro de retos_sesion_01, sino en la raiz.

Aqui esta las instrucciones para el reto de la sesión 02:

https://study.pylapaz.org/content/sesion02/#/62

**Comment by Brayanex14** [comment]
Ya lo solucione.
